### ISSUE TITLE
Please release source code!

### ISSUE THREAD

**Issue by coreybruce** [captainsouthbird/smb3#1]
Can you please release the source code so people can compile it for other platforms like Linux, Mac and other Unix systems.

**Comment by captainsouthbird** [comment]
... what? This is NES ASM source. If you mean for NESASM, I linked that project, which is not mine. But this will never compile for Linux, Mac, or anything else that's not literally an NES or Famicom.

**Comment by coreybruce** [comment]
Oh sorry for the confusion.
